### ISSUE TITLE
MultiPaper error with Citizens

### ISSUE THREAD

**Issue by Belceebuh** [MultiPaper/MultiPaper#354] opened 2023-02-19 07:33 UTC
Hello, I have the following problem with Citizens:

https://mclo.gs/4CtkbEr

I spoke to Citizens support and they told me that it is most likely a MultiPaper error plus they did not help me by finding the error.

**Comment by ham1255** [comment] 2023-02-19 07:39
this actually a bug within the stats manager in the server that uploads the stats back to the master

**Comment by Belceebuh** [comment] 2023-02-19 07:42
How can I solve it?

**Comment by ham1255** [comment] 2023-02-19 07:43
there is active Pull Request to fix it but it was not updated to 1.19.3

**Comment by Belceebuh** [comment] 2023-02-19 07:43
So all we can do is wait?

**Comment by ham1255** [comment] 2023-02-19 07:44
i might Pr my own solution later this day.

**Comment by Belceebuh** [comment] 2023-02-19 07:45
that would be great

**Comment by ham1255** [comment] 2023-02-21 17:18
Duplicate of #325

**Closed by ham1255** 2023-02-21 17:18 UTC
