### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by akosvr** [MultiPaper/MultiPaper#196] opened 2022-06-13 12:35 UTC
I found out how did they dupe on my server. 

1. Enchant an armor via anvil
3. Put that armor into a slot in your hands
4. Than quicly put that armor into a chest
5. Than the items that you put into that slot where the armor was, will get duped.

**Comment by akosvr** [comment] 2022-06-13 12:39
I also have a video of it, but it's in hungarian since a player sent it to me, if you need it, I can send it to you in discord private message

**Comment by PureGero** [comment] 2022-06-13 12:39
Language doesn't matter. Please send it as it would help to reproduce the glitch.

**Comment by akosvr** [comment] 2022-06-13 13:09
Okay, I sent it to you

**Comment by trxsson** [comment] 2023-02-17 15:39
Any chance this issue will be fixed any time soon? People on our server found out about it and that's a potential risk for our economy..

**Comment by ham1255** [comment] 2023-02-17 15:41
This marked as struggling to replicate, because devs cant replicate it, but there is many duplications that around

**Comment by trxsson** [comment] 2023-02-17 18:40
> This marked as struggling to replicate, because devs cant replicate it, but there is many duplications that around

Weird.. I takes some tries but usually it works after a bit. Sometimes using a new item or another item type seemed to help replicate it. After it's been done several times it stops working most of the time.

**Comment by ham1255** [comment] 2023-02-17 18:44
> > This marked as struggling to replicate, because devs cant replicate it, but there is many duplications that around
> 
> Weird.. I takes some tries but usually it works after a bit. Sometimes using a new item or another item type seemed to help replicate it. After it's been done several times it stops working most of the time.

do you have any video replicating this

**Comment by trxsson** [comment] 2023-03-26 09:26
> do you have any video replicating this
Sorry, I absolutely oversaw this one.
Here's a video of me replicating it. You can see that it fails multiple times but the last attempt worked.

https://user-images.githubusercontent.com/67932799/227766741-9032a551-0de7-4992-acec-4c28b66ab8c0.mp4

**Comment by Rushmead** [comment] 2023-03-26 14:55
Hi all, I've done some investigation into this and it appears this is caused by a bug from a Paper patch. The patch sorts the enchantments based on their ID when an item is enchanted through most means, however it seems like they missed out when an item is enchanted via an Anvil. When the item is sent to other servers to be synced, it gets passed through the `ItemStack.of` method which then sorts the enchantments, meaning that the Item on the server where it was originally enchanted is now out of sync with the server that the player is on due to the NBT tags not matching. This causes the duplication because as far as the server is aware, they are different items as the enchantments are in a different order. 

It looks like there are some open issues and PR's in the Paper repository related to this issue which haven't been solved / merged. I've written a quick patch (for 1.19.3 & 1.19.4) that would resolve this issue, however it is not ideal as it affects the order of enchantments which can be important when using an Anvil. It would be up to the maintainers as to if they wish to merge my patch. 

Please let me know if you have any questions.

**Comment by PureGero** [comment] 2023-03-28 03:54
Fixed by #365

**Closed by PureGero** 2023-03-28 03:54 UTC
Labels: Struggling to replicate
