### ISSUE TITLE
fallback multipaper master database and multipaper master database password protection.

### ISSUE THREAD

**Issue by kgncengiz** [MultiPaper/MultiPaper#403] opened 2024-07-09 03:34 UTC
### Is your feature request related to a problem?

multipaper's master database is a single point of failure in a multipaper server and there is no password protection in front of the multipaper master database which can lead to unauthorized connections.

### Describe the solution you'd like.

addition of password protection to multipaper master databases and being able to use multiple multipaper master databases at the same time and being able to set one of them as a fallback.

### Describe alternatives you've considered.

I can use a firewall instead of multipaper master password but it is not secure as a password. and there is no alternatives for the fallback database.

**Comment by PureGero** [comment] 2024-07-09 12:59
> use multiple multipaper master databases at the same time and being able to set one of them as a fallback.

Duplicate of #288

> there is no password protection in front of the multipaper master database which can lead to unauthorized connections.

Duplicate of #390

> I can use a firewall instead of multipaper master password but it is not secure as a password

No? A firewall can stop so many more attacks than a password. Plus, if someone gets your password, they can get in. But there's no password for a firewall, and thus they can not get in.

**Closed by PureGero** 2024-07-09 12:59 UTC
