### ISSUE TITLE
Opening a chest with generated loot causes the server to freeze

### ISSUE THREAD

**Issue by Jeleyk** [MultiPaper/MultiPaper#286] opened 2022-10-24 00:00 UTC
Opening a chest with generated loot causes the server to freeze a lot, and sometimes even crashes it.

**Comment by Madscience763** [comment] 2022-10-24 01:32
This is a bug on paper already. The treasure map looks for the first undiscovered location which causes the server to freeze. Not a multipaper issue

**Comment by xymb-endcrystalme** [comment] 2022-10-24 03:48
What's the easiest way to reproduce the bug?

**Comment by ham1255** [comment] 2022-10-24 03:55
Its just random, open a chest and boom

**Comment by ham1255** [comment] 2022-10-24 03:58
From purpur dev:
https://github.com/PurpurMC/Purpur/issues/1059#issuecomment-1187504382

**Comment by Madscience763** [comment] 2022-10-24 04:25
> What's the easiest way to reproduce the bug?

You can give yourself a chest with the loot table of a shipwreck. The further you are away from where the buried treasure would generate the longer the lag. will be. You will need to move around as once it finds one it will default to it until it has been explored. So either break the chest or tp around. 

/give @p minecraft:chest{BlockEntityTag:{LootTable:"chests/shipwreck_map"}}

**Comment by ham1255** [comment] 2022-10-24 05:01
I wonder, does generating chunks makes the issue less frequent?

**Comment by Madscience763** [comment] 2022-10-24 10:38
It can, it will still search a lot of chunks though even if it is pregenerated

**Comment by PureGero** [comment] 2022-10-24 20:55
Duplicate of PaperMC/Paper#7269

**Closed** 2022-10-24 20:57 UTC
