### ISSUE TITLE
The flight movements of the elytra are inconsistent

### ISSUE THREAD

**Issue by Shizuri23** [MultiPaper/MultiPaper#339] opened 2023-02-06 13:26 UTC
https://user-images.githubusercontent.com/46082179/216983084-8a98499b-dfd8-497d-8c33-77b399acfac2.mp4

**Comment by ham1255** [comment] 2023-02-06 13:31
kinda funny how players move like that, but since provided video shows 1.19.3 client having the issue i will assume that via version or any protocol translation plugin can cause this. try running same client version.

**Comment by Shizuri23** [comment] 2023-02-06 13:43
The client is also vanilla

**Comment by Shizuri23** [comment] 2023-02-06 13:46
> #316 must be related gotta check
> 
> but what multipaper version you are running? 1.19.3?

Current: git-MultiPaper-"843e95f" (MC: 1.19.3)*
Error obtaining version information
Previous version: git-MultiPaper-"f5e5dac" (MC: 1.19.3)

**Comment by ham1255** [comment] 2023-02-06 13:47
yup duplicate of #316

**Comment by ham1255** [comment] 2023-02-06 13:47
duplicate of #316

**Closed by ham1255** 2023-02-06 13:47 UTC
