### ISSUE TITLE
Prefix on 1.19.3 MultiPaper

### ISSUE THREAD

**Issue by Tynopia** [MultiPaper/MultiPaper#340] opened 2023-02-07 17:40 UTC
![image](https://user-images.githubusercontent.com/65678882/217321421-74225de8-cab4-4925-8b2f-8faddee1160a.png)
![image](https://user-images.githubusercontent.com/65678882/217321482-5f73f7c9-0d30-419a-9524-c322340527b8.png)
**This two pictures are made on the MultiPaper Server**

The Prefix of a Player are not working (Over the head) but in the Tablist. The Same code runs on the normal Paper 1.19.3 Server and it works... Is it possible to fix it?

**On a 1.19.2 MultiPaper Server it works**

![image](https://user-images.githubusercontent.com/65678882/217322203-28f4b70f-8750-4fd6-9fb0-eccd70da7bf9.png)

**Comment by ham1255** [comment] 2023-02-07 19:44
I think this duplicate of #316

**Comment by Tynopia** [comment] 2023-02-07 19:50
Yeah can be... How fast is it possible to fix? We would release our project and the deadline is soon... (Paulberger).
We must use 1.19.3 because of other plugins / inventory sync

**Comment by ham1255** [comment] 2023-02-07 19:51
> Yeah can be... How fast is it possible to fix? We would release our project and the deadline is soon... (Paulberger).
> 
> We must use 1.19.3 because of other plugins / inventory sync

Problem is really complex, servers get the animation but its not applying it.

**Comment by Tynopia** [comment] 2023-02-07 22:19
We currently don't have the resources to do it ourselves... It would be cool if you keep trying and persist... It's really important.

**Comment by ham1255** [comment] 2023-02-07 22:55
Duplicate of #316

**Closed by ham1255** 2023-02-07 22:55 UTC

**Comment by ham1255** [comment] 2023-02-08 18:36
update: it turns out to be plugin issue.
