### ISSUE TITLE
Blocks being updated while being mined can drop an item and still be placed

### ISSUE THREAD

**Issue by Madscience763** [MultiPaper/MultiPaper#232] opened 2022-08-04 18:04 UTC
https://user-images.githubusercontent.com/104371439/182915481-25688c66-9cbc-4f62-a674-a890d056aa70.mp4

https://user-images.githubusercontent.com/104371439/182915751-ba3655bd-aae8-4256-bc79-06046b00e8c1.mp4

This happens with powered rails, activator rails, pistons, sticky pistons, trapdoors (all types), redstone wire, doors,  and many other blocks that change state when redstone is applied. This only happens when the signal is going from the server you are on to a server to a chunk being processed by another server.

**Comment by PureGero** [comment] 2022-08-06 13:58
Duplicate of #204

**Comment by JonasDevDE** [comment] 2024-03-23 17:53
@PureGero why is this still open?

**Closed** 2024-03-23 17:54 UTC
Labels: bug, duplicate
